### ISSUE TITLE
Port the Imbued Sword

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/practicalities#11]
The Imbued Sword is an end game weapon. It is expensive to craft and can deal about 30 points of damage per hit. The art asset is already checked into source

1. It can be enchanted
2. It should not take any damage
3. it should be indestructible to fire/lava/explosions
4. it *can* despawn if left on the ground
5. It should have the flair "*Watch out for the quick draw!*" when you mouse over it

The recipe would be something like below where 'c' is the ImbuedCore and 'd' is a diamond rod.

" c "
" c "
" d "

**Comment by joekaiser** [comment]
I am open to changing the recipe. It is just a thought for now. It would be cool if you had to "active" the item through some ritual. Meaning once you craft it, it doesn't take on the end-game properties listed above until you do something else.

**Comment by thecodewarrior** [comment]
Maybe it could also always do critical hits.
