### ISSUE TITLE
Distribute items piped into the Wither Killer

### ISSUE THREAD

**Issue by blisterfingers** [joekaiser/practicalities#2]
Right now, if I pipe in Wither Skulls, it will entirely fill up one slot, then the next, then the next, meaning I need at least 129 skulls before it will begin fully automatically doing it's thing. Same applies to the Soul Sand.

While there may be some pipe systems that will distribute items into each slot, I propose that the Killer should do this automatically, placing piped in items into the slot with the least amount of that item in.

**Comment by joekaiser** [comment]
This is by design. It forces you to have a way to automate skulls before you can automate stars. If you do have more than 3 stacks of skulls, just prime the killer yourself.

**Comment by blisterfingers** [comment]
Why would you want to force people to have automated skulls before automating the Killer? If someone went to the trouble of killing that many skeletons by hand, I'd say let 'em pipe them in from a chest. they've earned it. But hey, it's your mod and a fine mod it is too.

**Comment by joekaiser** [comment]
Because it doesn't take any extra effort to insert a stack of skulls into the killer than it does a chest. You would still have to put them somewhere

**Comment by blisterfingers** [comment]
But that somewhere, for me at least, is in another dimension. 

For example; People could bury their killer under the floor and just have input and output chests visible in their base or any number of possible other set-ups. That's part of the beauty of modded mc. 

To me, the way it works at the moment, would be akin to having a furnace that won't smelt until it has a full stack of mats and then will only smelt one item until it fills up again. It just makes things awkward and leaves a bunch of mats unused unless you micro-manage.
