### ISSUE TITLE
Player Interface

### ISSUE THREAD

**Issue by thecodewarrior** [joekaiser/practicalities#22]
Other than PneumaticCraft I don't know of very many mods that add a player interface block. It's kind of something that would be pretty practical to have around, but some packs \*cough\**Infinity*\*cough* don't include PneumaticCraft.

I think it would be cool to have one, it should also have a GUI where you can select what slots should be exposed.

A few other cool stuff that could be added would be:

- Charging items - Make it accept RF to charge items in the player's inventory. The charge should be round-robin
- Feeding the player - Make it accept Nutrient Distillation (EnderIO) or an equivalent (Pre-Chewed Food) from Practicalities. It would use maybe 100mb per shank. Always topping off both hunger and saturation.

Pre-chewed food should be created by putting water and two or more different food items into an Industrial Masher, which would create Pre-Chewed Food based on the average hunger+saturation of the two foods.

**Comment by thecodewarrior** [comment]
The texture for Pre-Chewed Food (It's a fluid) should be a sickly brownish-green with some red, green, and white specks floating around.

**Comment by joekaiser** [comment]
Given that this would charge and feed you, what if it could act like a bed? 


Maybe this is two blocks? One a player interface and the other a "respawn station" that would make sure you are good to go

**Comment by thecodewarrior** [comment]
Maybe it could also be able to teleport you back, at the cost of a lot of power and a few ender pearls.

**Comment by thecodewarrior** [comment]
*teleport you from wherever to the respawn station, not to where you died. But that might work too.
