### ISSUE TITLE
Duplication glitch with Anti-Builders from Artifacts when paired with Practicalities Matter Transposer

### ISSUE THREAD

**Issue by Freelanci** [joekaiser/practicalities#30]
I'm reporting this dupe bug from a Modsauce 2 multiplayer server; modpack provided through ATLauncher. When using the Matter Transporter item from the Practicalities mod in the range of an anti-builder typically found in the ruined towers, the block picked up by the matter transporter is immediately replaced, and the transporter retains a copy of the block, which can then be placed down; effectively replicating the block.

I will also be posting this issue on Artifacts side.

**Comment by joekaiser** [comment]
This is a known issue, and affects any mod that tries to move blocks with an anti builder nearby. Sadly, there isn't anything I will do about it. The anti builder creates a new block when one is removed
