### ISSUE TITLE
Port the Sitis Stick

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/practicalities#4]
The Sitis Stick is an item that when used and "used" will stop the rain. It doesn't just set the weather to clear, it needs to reset the timer as well so it doesn't start raining right away. Think of "sleeping" without resetting your spawn point.

**Comment by thecodewarrior** [comment]
So by "used" I assume you mean it is consumed in the process? And does the stick stack?

**Comment by joekaiser** [comment]
It doesn't stack, and "used" like a magic wand. Right click when you are holding it.  I don't think it is going to be the cheapest thing to make, so it would be nice if it could be used more than 1 time. Maybe it had a durability? We can always change the number of uses later, but lets start with 10. 

Attached is an image for it 
![image](https://cloud.githubusercontent.com/assets/1521110/11402008/7de72902-934a-11e5-8045-9e04bc10ffe6.png)

**Comment by thecodewarrior** [comment]
What should the recipe be? I was thinking this:

X  R  V
X  D  R
R  X  X
X = nothing, R = Blaze rod, V = void bucket, D = diamond

**Comment by joekaiser** [comment]
I'm not sure. Make it whatever for now. We can always tweak it. I am porting a few "base crafting" items over this weekend. Like a diamond rod which could be used.

Try to follow how the current project does things. If you have As let me know

Sent from Nine
