### ISSUE TITLE
Item at a time from magnet

### ISSUE THREAD

**Issue by koalalord9999** [joekaiser/practicalities#48]
(I'm in 1.7.10 - but I don't think it's a feature later)
So, my issue is, I've got a dev\null\ in my inventory collecting cobblestone, right? When I mine anything while my magnet is on (Rare earth magnet, I think this has changed names in later versions) it seems to skip the player picked up, and goes nearly straight into my inventory. By passing the player picked up, it makes my dev null useless, as cobble will not go into it if that code is skipped.

So was just thinking, that if you update 1.7.10 still (if not, thats fine too) adding the feature to allow the dev\null\ to work with the magnet, that would be great!

Thanks :)

**Comment by joekaiser** [comment]
Yup, already fixed for the next update :) Thanks for reporting it though.
